# This is a basic workflow to help you get started with Actions

name: ASP-NET-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # setup MS Build  
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.2
      #  Setup Nuget for use with Actions
      - name: Setup Nuget.exe
        uses: Nuget/setup-nuget@v1.0.2
      - name: Restore NuGet Packages
        run: nuget restore WebApplication2.sln
 
      - name: Build and Publish Web App
        run: msbuild WebApplication2.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
 
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
         name: published_webapp
         path: bin\Release\Publish  
